# -*- coding: utf-8 -*-
"""
A2A Registry Extension Point

This module defines the abstract interface for A2A protocol registry
implementations. Registry implementations are responsible for registering
agent services to service discovery systems (e.g., Nacos, Consul, etc.).
"""
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Optional, Any

from a2a.types import AgentCard

__all__ = [
    "A2ARegistry",
    "DeployProperties",
    "A2aTransportsProperties",
]

logger = logging.getLogger(__name__)


@dataclass
class DeployProperties:
    """Deployment properties containing runtime configuration information.

    This class contains deployment-related information such as host address,
    port number, root path, and other runtime configuration that may be
    needed for service registration.

    Attributes:
        host: Server host address
        port: Server port number
        root_path: Application root path (e.g., from FastAPI app.root_path)
        base_url: Base URL for the service
        extra: Additional deployment properties provided as dict
    """

    host: Optional[str] = None
    port: Optional[int] = None
    root_path: str = ""
    base_url: Optional[str] = None
    extra: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        """Initialize extra dict if not provided."""
        if self.extra is None:
            self.extra = {}


@dataclass
class A2aTransportsProperties:
    """A2A transport properties for individual transport configurations.

    Each transport may have its own configuration including type, URL,
    port, path, and other transport-specific settings.

    Attributes:
        transport_type: Type of transport (e.g., "JSONRPC", "gRPC")
        url: Transport URL
        host: Transport-specific host address (optional)
        port: Transport-specific port number (optional)
        path: Transport-specific path (optional)
        root_path: Transport root path (optional)
        sub_path: Transport sub path (optional)
        tls: TLS configuration (optional)
        extra: Additional transport-specific properties
    """

    transport_type: str
    url: Optional[str] = None
    host: Optional[str] = None
    port: Optional[int] = None
    path: Optional[str] = None
    root_path: Optional[str] = None
    sub_path: Optional[str] = None
    tls: Optional[Dict[str, Any]] = None
    extra: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        """Initialize extra dict if not provided."""
        if self.extra is None:
            self.extra = {}


class A2ARegistry(ABC):
    """Abstract base class for A2A protocol registry implementations.

    Registry implementations handle the registration of A2A agent services
    to service discovery systems. This provides an extension point for
    different registry backends (Nacos, Consul, etc.).

    Registry registration is optional and failures should not block the
    runtime startup process. Multiple registry implementations can be
    configured and will be tried sequentially.

    Subclasses should implement the registry_name and register methods.
    """

    @abstractmethod
    def registry_name(self) -> str:
        """Get the name of this registry implementation.

        Returns:
            Registry name (e.g., "nacos", "consul")
        """
        raise NotImplementedError("Subclasses must implement registry_name()")

    @abstractmethod
    def register(
        self,
        agent_card: AgentCard,
        deploy_properties: DeployProperties,
        a2a_transports_properties: List[A2aTransportsProperties],
    ) -> None:
        """Register an A2A agent service to the registry.

        This method is called after the A2A routes have been added to the
        FastAPI application and the AgentCard has been generated. It should
        perform the registration of the agent service to the service discovery
        system.

        Registry implementations can decide whether to register the AgentCard
        and/or the corresponding TransportEndpoints based on the provided
        configuration.

        Args:
            agent_card: The complete A2A agent card generated by runtime
                based on user-created agent information and configured
                agentCard information
            deploy_properties: Deployment properties including runtime
                configuration such as host address, port number, etc.
            a2a_transports_properties: List of transport properties for
                multiple A2A Server transports. Each transport may have
                independent configuration such as different port numbers,
                paths, etc.

        Raises:
            Exception: Registration failures should be raised as exceptions
                but will be caught and logged by the caller, not blocking
                the startup process.
        """
        raise NotImplementedError("Subclasses must implement register()")
