# -*- coding: utf-8 -*-
"""
Nacos Registry Implementation for A2A Protocol

This module provides a Nacos-based registry implementation for A2A protocol
agent service registration. It serves as the default registry implementation
for A2A protocol adapters.
"""
import asyncio
import logging
import os
from typing import List, Optional

from a2a.types import AgentCard
from v2.nacos import ClientConfig, ClientConfigBuilder
from v2.nacos.ai.model.ai_param import (
    RegisterAgentEndpointParam,
    ReleaseAgentCardParam,
)
from v2.nacos.ai.nacos_ai_service import NacosAIService

from .a2a_registry import (
    A2ARegistry,
    DeployProperties,
    A2aTransportsProperties,
)

logger = logging.getLogger(__name__)


class NacosRegistry(A2ARegistry):
    """Nacos-based registry implementation for A2A protocol.

    This registry registers A2A agent services to Nacos service discovery system.
    It performs two-step registration:
    1. Publishes agent card to Nacos (agent metadata)
    2. Registers agent endpoint with host/port information (service location)

    Args:
        nacos_client_config: Optional Nacos client configuration.
            If None, creates default config from environment variables.
    """

    def __init__(
        self,
        nacos_client_config: Optional[ClientConfig] = None,
    ):
        self._nacos_client_config = nacos_client_config
        self._nacos_ai_service: Optional[NacosAIService] = None
        self._register_task: Optional[asyncio.Task] = None

    def registry_name(self) -> str:
        """Get the name of this registry implementation.

        Returns:
            Registry name: "nacos"
        """
        return "nacos"

    def register(
        self,
        agent_card: AgentCard,
        deploy_properties: DeployProperties,
        a2a_transports_properties: List[A2aTransportsProperties],
    ) -> None:
        """Register an A2A agent service to Nacos.

        Args:
            agent_card: The complete A2A agent card generated by runtime
            deploy_properties: Deployment properties including host, port, root_path
            a2a_transports_properties: List of transport properties for multiple
                A2A Server transports

        Raises:
            Exception: If registration fails
        """
        host = deploy_properties.host or "127.0.0.1"
        port = deploy_properties.port
        root_path = deploy_properties.root_path or ""

        if port is None:
            logger.warning(
                "[NacosRegistry] Port not specified in deploy_properties, "
                "skipping endpoint registration"
            )
            return

        logger.info(
            "[NacosRegistry] Registering agent=%s at %s:%s%s",
            agent_card.name,
            host,
            port,
            root_path,
        )

        self._start_register_task(
            agent_card=agent_card,
            host=host,
            port=port,
            root_path=root_path,
        )

        if a2a_transports_properties:
            logger.debug(
                "[NacosRegistry] Additional transports available: %d",
                len(a2a_transports_properties),
            )

    def _start_register_task(
        self,
        agent_card: AgentCard,
        host: str,
        port: int,
        root_path: str,
    ) -> None:
        """Start background Nacos registration task."""
        try:
            loop = asyncio.get_running_loop()
            self._register_task = loop.create_task(
                self._register_to_nacos(
                    agent_card=agent_card,
                    host=host,
                    port=port,
                    root_path=root_path,
                )
            )
            logger.info("[NacosRegistry] Registration task started in background")
        except RuntimeError:
            logger.warning(
                "[NacosRegistry] No running event loop, skipping registration."
            )

    def _get_client_config(self) -> ClientConfig:
        """Get Nacos client configuration.

        Returns:
            ClientConfig: Nacos client configuration
        """
        if self._nacos_client_config is not None:
            return self._nacos_client_config

        server_addr = os.getenv("NACOS_SERVER_ADDR", "localhost:8848")
        builder = ClientConfigBuilder().server_address(server_addr)

        nacos_username = os.getenv("NACOS_USERNAME")
        nacos_password = os.getenv("NACOS_PASSWORD")
        if nacos_username and nacos_password:
            builder.username(nacos_username).password(nacos_password)
            logger.debug(
                "[NacosRegistry] Using authentication: username=%s",
                nacos_username,
            )

        return builder.build()

    async def _register_to_nacos(
        self,
        agent_card: AgentCard,
        host: str,
        port: int,
        root_path: str,
    ) -> None:
        """Register agent to Nacos.

        Performs two-step registration:
        1. Release agent card to Nacos
        2. Register agent endpoint with host/port information

        Args:
            agent_card: The A2A agent card to register
            host: Server host address
            port: Server port
            root_path: Application root path

        Raises:
            Exception: If registration fails
        """
        try:
            client_config = self._get_client_config()
            self._nacos_ai_service = await NacosAIService.create_ai_service(
                client_config
            )

            # Publish agent card
            await self._nacos_ai_service.release_agent_card(
                ReleaseAgentCardParam(agent_card=agent_card)
            )
            logger.info(
                "[NacosRegistry] Agent card published: agent=%s",
                agent_card.name,
            )

            # Register agent endpoint
            await self._nacos_ai_service.register_agent_endpoint(
                RegisterAgentEndpointParam(
                    agent_name=agent_card.name,
                    version=agent_card.version,
                    address=host,
                    port=port,
                    path=root_path,
                )
            )
            logger.info(
                "[NacosRegistry] Agent endpoint registered: agent=%s, "
                "address=%s:%s, path=%s",
                agent_card.name,
                host,
                port,
                root_path,
            )

        except Exception as e:
            logger.error(
                "[NacosRegistry] Failed to register agent=%s: %s",
                agent_card.name,
                str(e),
                exc_info=True,
            )
            raise
